### ISSUE TITLE
Crash after setting budgets

### ISSUE THREAD

**Issue by siwei-s** [rarfell/dimeApp#4]
Even if I re-install the app, it keeps crashing. Now I can't even use it.

I just follow the steps to set up a budget, but the final step didn't let me finish: clicking ✅ button doesn't work. After that, I have the crashing issue.

iOS version: 15.6.1

**Comment by ashishpawar517** [comment]
This is happening on ios 16.2 also, can you please fix this @rarfell

**Comment by rarfell** [comment]
Hey all, this should be fixed as of Version 2!
